--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
AttributeError: 'QNode' object has no attribute 'qtape'. Did you mean: '_tape'?
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
AttributeError: 'QNode' object has no attribute 'tape'. Did you mean: '_tape'?
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
TypeError: cannot unpack non-iterable function object
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
TypeError: run_adapt_vqe.<locals>.pool_qnode() missing 1 required positional argument: 'params'
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
AttributeError: LightningQubit has no attribute 'batch_execute'. You may be looking for a property or method present in the legacy device interface. Please consult the LightningQubit documentation for an updated list of public properties and methods.
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
TypeError: LightningQubit.__init__() got an unexpected keyword argument 'interface'
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.1
Exit Code: 1
LAST OUTPUT:
TypeError: LightningQubit.__init__() got an unexpected keyword argument 'interface'
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer Adam --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer Adam --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer Adam --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer COBYLA --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer COBYLA --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer COBYLA --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer L-BFGS-B --lr 0.0
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer SPSA --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer SPSA --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer Adam --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer Adam --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer Adam --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer COBYLA --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer COBYLA --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer COBYLA --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz k-UpCCGSD --optimizer L-BFGS-B --lr 0.0
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer SPSA --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer SPSA --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer Adam --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer Adam --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer Adam --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer COBYLA --lr 0.2
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer COBYLA --lr 0.1
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer COBYLA --lr 0.05
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz HEA --optimizer L-BFGS-B --lr 0.0
Exit Code: 1
LAST OUTPUT:
IndentationError: unexpected indent
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
NameError: name 'step_fn' is not defined
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
UnboundLocalError: cannot access local variable 'e' where it is not associated with a value
--- FAILED CONFIGURATION ---
Command: /Users/omtailor/anaconda3/envs/asphalt-qchem-p3/bin/python -u src/experiment_driver.py --ansatz ADAPT-VQE --optimizer SPSA --lr 0.2
Exit Code: 1
LAST OUTPUT:
TypeError: Can't find vector space for value -1863.4990234375 of type <class 'jaxlib.xla_extension.ArrayImpl'>. Valid types are dict_keys([<class 'autograd.core.SparseObject'>, <class 'list'>, <class 'tuple'>, <class 'dict'>, <class 'numpy.ndarray'>, <class 'float'>, <class 'numpy.longdouble'>, <class 'numpy.float64'>, <class 'numpy.float32'>, <class 'numpy.float16'>, <class 'complex'>, <class 'numpy.clongdouble'>, <class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'numpy.linalg.linalg.EigResult'>, <class 'numpy.linalg.linalg.EighResult'>, <class 'numpy.linalg.linalg.QRResult'>, <class 'numpy.linalg.linalg.SlogdetResult'>, <class 'numpy.linalg.linalg.SVDResult'>, <class 'pennylane.numpy.tensor.tensor'>])
